"""
Validator and extractor for code generated by LLM providers.

Enforces deterministic boundary cleaning:
1. Strips markdown code fences (```cpp, ```python, etc.)
2. Strips conversational prose wrappers
3. Verifies non-empty and basic structural sanity
Does NOT pretend to be a full compiler.
"""

import re
from src.utils.errors import SolverError


class SolutionValidator:
    """Cleans and validates LLM-generated code solutions."""

    @classmethod
    def clean_and_validate(cls, raw_response: str, language: str = "C++") -> str:
        """
        Extract clean source code from raw model response and perform basic sanity checks.

        Raises:
            SolverError: If no valid source code could be extracted.
        """
        if not raw_response or not raw_response.strip():
            raise SolverError("Provider returned empty response")

        text = raw_response.strip()

        # 1. Extract from markdown code fences if present
        fence_match = re.search(r"```(?:[a-zA-Z0-9_+-]*)\n?(.*?)```", text, re.DOTALL)
        if fence_match:
            code = fence_match.group(1).strip()
        else:
            # If no closing fence or raw code
            code = text

        # 2. Strip leading conversational prose before the first code line
        lines = code.splitlines()
        code_start_idx = 0
        lang_lower = language.lower()

        for idx, line in enumerate(lines):
            stripped = line.strip()
            if not stripped:
                continue

            # In C/C++: starts with #include, using namespace, int main, void, struct, template
            if lang_lower in ("c", "c++"):
                if stripped.startswith(("#", "using ", "int main", "void ", "struct ", "class ", "template", "//", "/*")):
                    code_start_idx = idx
                    break
            # In Java: starts with import, public class, class, package
            elif lang_lower == "java":
                if stripped.startswith(("import ", "package ", "public class", "class ", "/*", "//")):
                    code_start_idx = idx
                    break
            # In Python: starts with import, from, def, class, if, or variable/comment
            elif lang_lower == "python":
                if stripped.startswith(("import ", "from ", "def ", "class ", "if ", "#", "sys.", "for ", "while ")):
                    code_start_idx = idx
                    break
            else:
                # Other languages: first non-empty line
                code_start_idx = idx
                break

        lines = lines[code_start_idx:]

        # 3. Strip trailing conversational prose (e.g. Explanation:, Note:, Complexity:)
        trimmed_lines = []
        for line in lines:
            stripped = line.strip()
            if stripped.startswith((
                "Explanation:", "Note:", "Complexity:", "Time Complexity:",
                "Space Complexity:", "How it works:", "Approach:", "Here is a breakdown:"
            )):
                break
            trimmed_lines.append(line)

        # Strip any trailing fence lines if present
        while trimmed_lines and trimmed_lines[-1].strip() == "```":
            trimmed_lines.pop()

        cleaned_code = "\n".join(trimmed_lines).strip()

        # 4. Non-empty check
        if not cleaned_code:
            raise SolverError("Cleaned source code is empty after extracting from model response")

        # 5. Basic structural sanity check
        cls._verify_structural_sanity(cleaned_code, language)

        return cleaned_code

    @classmethod
    def _verify_structural_sanity(cls, code: str, language: str) -> None:
        """Perform minimal sanity check to prevent injecting pure conversational prose."""
        lang_lower = language.lower()

        if lang_lower in ("c", "c++"):
            # C/C++ must have a main function
            if "main" not in code:
                raise SolverError("Generated C/C++ code lacks a 'main' function")
        elif lang_lower == "java":
            # Java must have a class or main method
            if "class" not in code or "main" not in code:
                raise SolverError("Generated Java code lacks a class or 'main' method")
        elif lang_lower == "python":
            # Python should have at least 1 line of executable code
            non_comments = [l for l in code.splitlines() if l.strip() and not l.strip().startswith("#")]
            if not non_comments:
                raise SolverError("Generated Python code contains only comments or whitespace")
